services:
  authelia:
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    depends_on:
      authelia-redis:
        condition: service_healthy
      authelia-db:
        condition: service_healthy
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      AUTHELIA_STORAGE_MYSQL_PASSWORD: ${AUTHELIA_STORAGE_MYSQL_PASSWORD}
    volumes:
      - authelia-config:/config
      - ./configuration.yml:/config/configuration.yml:ro
      - ./users_database.yml:/config/users_database.yml:ro

  authelia-redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass ${AUTHELIA_REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${AUTHELIA_REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - authelia-redis:/data

  authelia-db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: authelia
      MYSQL_USER: authelia
      MYSQL_PASSWORD: ${AUTHELIA_STORAGE_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${AUTHELIA_STORAGE_MYSQL_ROOT_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p${AUTHELIA_STORAGE_MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - authelia-mysql:/var/lib/mysql

volumes:
  authelia-config: {}
  authelia-redis: {}
  authelia-mysql: {}
