services:
  supabase-studio:
    image: supabase/studio:latest
    restart: unless-stopped
    expose:
      - 3000
    environment:
      STUDIO_DEFAULT_ORGANIZATION: ${STUDIO_DEFAULT_ORGANIZATION}
      STUDIO_DEFAULT_PROJECT: ${STUDIO_DEFAULT_PROJECT}
