services:
  mailserver:
    image: analogic/poste.io
    restart: unless-stopped
    hostname: mail.${DOMAIN}
    environment:
      - TZ=${TZ}
      - HTTPS=OFF
      - HTTP_PORT=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - poste-data:/data

volumes:
  poste-data: {}
