services:
  strapi:
    image: elestio/strapi-production:v5.33.0
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 1337
    environment:
      NODE_ENV: production
      STRAPI_TELEMETRY_DISABLED: true
      STRAPI_PLUGIN_I18N_INIT_LOCALE_CODE: en
      FAST_REFRESH: true
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    volumes:
      - strapi-data:/srv/app
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:1337"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi -d strapi"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - strapi-database:/var/lib/postgresql

volumes:
  strapi-data: {}
  strapi-database: {}
