[variables]
db_password = "${password:32}"
[config]

[[config.domains]]
serviceName = "mealie"
port = 9000
host = "${domain}"

[config.env]
ALLOW_SIGNUP = "false"
TZ = "Europe/Rome"
DB_PASSWORD = "${db_password}"
