services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    expose:
      - 1880
    environment:
      TZ: ${TZ}
      NODE_RED_CREDENTIAL_SECRET: ${NODE_RED_CREDENTIAL_SECRET}
    volumes:
      - node-red-data:/data

volumes:
  node-red-data: {}
