
services:
  lodestone:
    image: ghcr.io/lodestone-team/lodestone_core
    volumes:
      - lodestone:/home/user/.lodestone
    restart: unless-stopped

  lodestone_dashboard:
    image: ghcr.io/lodestone-team/lodestone_dashboard:v0.5.1
    restart: always  

volumes:
  lodestone:
    driver: local