[variables]
db_password = "${password:32}"
db_root_password = "${password:32}"
secret = "${password:64}"
[config]

[[config.domains]]
serviceName = "directus"
port = 8055
host = "${domain}"

[config.env]
DB_CLIENT = "mysql"
DB_HOST = "db"
DB_PORT = "3306"
DB_DATABASE = "directus"
DB_USER = "directus"
DB_PASSWORD = "${db_password}"
DB_ROOT_PASSWORD = "${db_root_password}"
SECRET = "${secret}"
