services:
  app:
    image: jc21/nginx-proxy-manager:2.15.1
    restart: unless-stopped
    expose:
      - 81
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ}
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt

volumes:
  npm-data: {}
  npm-letsencrypt: {}
