services:
  grafana:
    image: grafana/grafana-enterprise:12.4.9
    restart: unless-stopped
    expose:
      - 3000
    environment:
      GF_DATABASE_TYPE: ${GF_DATABASE_TYPE}
      GF_DATABASE_HOST: ${GF_DATABASE_HOST}
      GF_DATABASE_NAME: ${GF_DATABASE_NAME}
      GF_DATABASE_USER: ${GF_DATABASE_USER}
      GF_DATABASE_PASSWORD: ${GF_DATABASE_PASSWORD}
      GF_SECURITY_SECRET_KEY: ${GF_SECURITY_SECRET_KEY}
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      grafana-db:
        condition: service_healthy

  grafana-db:
    image: postgres:18.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: ${GF_DATABASE_PASSWORD}
      POSTGRES_DB: grafana
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafana -d grafana"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - grafana-postgres:/var/lib/postgresql

volumes:
  grafana-storage: {}
  grafana-postgres: {}
