[variables]
uid = "1000"
gid = "1000"
timezone = "Europe/Rome"

[config]

[[config.domains]]
serviceName = "syncthing"
port = 8_384
host = "${domain}"

[config.env]
PUID = "${uid}"
PGID = "${gid}"
TZ = "${timezone}"
