[variables]
admin_password = "${password:32}"
[config]

[[config.domains]]
serviceName = "seafile"
port = 80
host = "${domain}"

[config.env]
SEAFILE_SERVER_HOSTNAME = "${domain}"
SEAFILE_SERVER_PROTOCOL = "https"
SEAFILE_ADMIN_EMAIL = "admin@example.com"
SEAFILE_ADMIN_PASSWORD = "${admin_password}"
