services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - nginx-config:/etc/nginx
      - nginx-html:/usr/share/nginx/html
volumes:
  nginx-config: {}
  nginx-html: {}