services:
  app:
    image: jc21/nginx-proxy-manager:2.15.1
    restart: unless-stopped
    expose:
      - 81
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ}
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: npm
    volumes:
      - npm-data:/data
      - npm-letsencrypt:/etc/letsencrypt
    depends_on:
      db:
        condition: service_healthy

  db:
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - npm-mariadb:/config
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mariadb-admin ping -h 127.0.0.1 -uroot -p"$${MYSQL_ROOT_PASSWORD}"',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  npm-data: {}
  npm-letsencrypt: {}
  npm-mariadb: {}
