services:
  rsshub:
    image: diygod/rsshub:2026-09-07
    restart: unless-stopped
    expose:
      - 1200
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - rsshub-data:/app/data

volumes:
  rsshub-data: {}
