[variables]
app_keys = "${password:64}"
jwt_secret = "${password:64}"
api_token_salt = "${password:64}"
admin_jwt_secret = "${password:64}"
transfer_token_salt = "${password:64}"
encryption_key = "${password:64}"
[config]

[[config.domains]]
serviceName = "strapi"
port = 1337
host = "${domain}"

[config.env]
DATABASE_CLIENT = "sqlite"
DATABASE_FILENAME = "/srv/app/.tmp/data.db"
HOST = "0.0.0.0"
PORT = "1337"
NODE_ENV = "development"
APP_KEYS = "${app_keys}"
API_TOKEN_SALT = "${api_token_salt}"
ADMIN_JWT_SECRET = "${admin_jwt_secret}"
TRANSFER_TOKEN_SALT = "${transfer_token_salt}"
JWT_SECRET = "${jwt_secret}"
ENCRYPTION_KEY = "${encryption_key}"
