services:
  garage:
    image: dxflrs/garage:v2.4.1
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage-storage:/var/lib/garage
    restart: unless-stopped

volumes:
  garage-storage: {}
