services:
  adguard:
    image: adguard/adguardhome:v0.107.79
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf

volumes:
  adguard-work: {}
  adguard-conf: {}
