services:
  stalwart-mail:
    image: stalwartlabs/stalwart:latest-alpine # for production choose specific version from https://hub.docker.com/r/stalwartlabs/stalwart/tags
    volumes:
      - stalwart_data:/opt/stalwart-mail
    restart: unless-stopped

volumes:
  stalwart_data: