[variables]
db_password = "${password:32}"
db_root_password = "${password:32}"
admin_password = "${password:32}"
admin_api_password = "${password:32}"
[config]

[[config.domains]]
serviceName = "freshrss"
port = 80
host = "${domain}"

[config.env]
TZ = "Europe/Rome"
FRESHRSS_DOMAIN = "${domain}"
DB_PASSWORD = "${db_password}"
DB_ROOT_PASSWORD = "${db_root_password}"
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "${admin_password}"
ADMIN_API_PASSWORD = "${admin_api_password}"
