services:
  homebridge:
    image: homebridge/homebridge:2026-09-02
    restart: unless-stopped
    expose:
      - 8581
    environment:
      HOMEBRIDGE_CONFIG_UI_PORT: ${HOMEBRIDGE_CONFIG_UI_PORT}
    volumes:
      - homebridge-data:/homebridge

volumes:
  homebridge-data: {}
