[config]

[[config.domains]]
serviceName = "gitlab"
port = 80
host = "${domain}"

[config.env]
GITLAB_OMNIBUS_CONFIG = "external_url 'https://${domain}'; gitlab_rails['nginx']['listen_port'] = 80; gitlab_rails['nginx']['listen_https'] = false; letsencrypt['enable'] = false"
