services:
  erpnext:
    image: frappe/erpnext:v15
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites

volumes:
  erpnext-sites: {}
