services:
  flowise:
    image: flowiseai/flowise:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 3000
    environment:
      PORT: ${PORT}
      DATABASE_TYPE: mariadb
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: flowise
      DATABASE_USER: flowise
      DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - flowise-data:/root/.flowise

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: flowise
      MARIADB_USER: flowise
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h localhost -u root -p${DB_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - flowise-database:/var/lib/mysql

volumes:
  flowise-data: {}
  flowise-database: {}
