services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    expose:
      - 9090
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  prometheus-data: {}
