services:
  ollama:
    image: ollama/ollama:0.33.3
    restart: unless-stopped
    expose:
      - 11434
    environment:
      OLLAMA_HOST: ${OLLAMA_HOST}

    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data: {}
