[variables]
db_password = "${password:32}"
[config]

[[config.domains]]
serviceName = "odoo"
port = 8069
host = "${domain}"

[config.env]
DB_PASSWORD = "${db_password}"
POSTGRES_PASSWORD = "${db_password}"
