services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:16.0.3
    restart: unless-stopped
    expose:
      - 3000
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
      FORGEJO__database__DB_TYPE: ${FORGEJO__database__DB_TYPE}
      FORGEJO__database__PATH: ${FORGEJO__database__PATH}
      FORGEJO__server__ROOT_URL: ${FORGEJO__server__ROOT_URL}
      FORGEJO__server__DOMAIN: ${FORGEJO__server__DOMAIN}
      FORGEJO__server__DISABLE_SSH: ${FORGEJO__server__DISABLE_SSH}
    volumes:
      - forgejo-data:/data
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/"]
      interval: 15s
      timeout: 5s
      retries: 10

volumes:
  forgejo-data: {}
