[variables]
secret_key = "${hash:64}"

[config]
mounts = []

[[config.domains]]
serviceName = "paperless-webserver"
port = 8_000
host = "${domain}"

[config.env]
PAPERLESS_SECRET_KEY = "${secret_key}"
PAPERLESS_URL = "https://${domain}"
PAPERLESS_REDIS = "redis://paperless-broker:6379"
PAPERLESS_DBENGINE = "sqlite3"
PAPERLESS_DBHOST = ""
